- name: Verificación de Código, Tests y Cobertura (Lint & JaCoCo)
  run: ./gradlew lint jacocoTestReport

- name: Análisis Estático con SonarQube CLI
  uses: SonarSource/sonarqube-scan-action@v4
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: "http://nattech.fib.upc.edu:40380"
  with:
    args: >
      -Dsonar.projectKey=GitHardUPCFrontend
      -Dsonar.projectName="GitHardUPC Frontend"
      -Dsonar.sources=app/src/main/java
      -Dsonar.tests=app/src/test/java,app/src/androidTest/java
      -Dsonar.java.binaries=app/build/tmp/kotlin-classes/debug
      -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
